// SitePlan V60 procurement enhancements
(()=>{
const style=document.createElement('style');style.textContent='\n    /* V60 procurement workspace */\n    .tender-status-bar{display:flex;gap:7px;flex-wrap:wrap;align-items:center;margin:14px 0 18px;padding:12px;background:#0d1116;border:1px solid var(--line);border-radius:12px}.tender-status-bar .label{font-size:11px;color:var(--muted);font-weight:900;text-transform:uppercase;margin-right:4px}.tender-status-bar .btn.active{border-color:var(--green);color:var(--green)}\n    .quote-summary-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin:12px 0 16px}.quote-summary-card{border:1px solid var(--line);border-radius:12px;padding:12px;background:#0d1116}.quote-summary-card span{display:block;color:var(--muted);font-size:10px;text-transform:uppercase;font-weight:900}.quote-summary-card b{display:block;font-size:18px;margin-top:4px}.quote-table-wrap{overflow:auto;border:1px solid var(--line);border-radius:12px}.quote-table-wrap .quote-table{margin:0;min-width:1050px}.quote-table tr.best{background:rgba(168,255,53,.055)}.quote-detail{max-width:220px;white-space:normal;line-height:1.35}.attachment-list{display:grid;gap:8px;margin-top:10px}.attachment-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:11px 12px;border:1px solid var(--line);border-radius:10px;background:#0d1116}.attachment-row small{color:var(--muted)}\n    @media(max-width:800px){.quote-summary-grid{grid-template-columns:1fr 1fr}}\n';document.head.appendChild(style);

openTenderView=function(id){
 const t=tenders.find(x=>x.id===id);if(!t)return;
 const qs=t.quotes||[], priced=qs.filter(q=>Number(q.total)>0), lowest=priced.length?Math.min(...priced.map(q=>Number(q.total))):0, highest=priced.length?Math.max(...priced.map(q=>Number(q.total))):0;
 const awarded=qs.find(q=>q.status==='awarded');
 const quotes=qs.map(q=>{const best=lowest&&Number(q.total)===lowest;return `<tr class="${best?'best':''}"><td><b>${esc(q.company)}</b>${best?'<br><small style="color:var(--green);font-weight:900">LOWEST QUOTE</small>':''}<br><small>${esc(q.email||'')}</small></td><td>${esc(q.contact||'—')}</td><td>${q.net?money(q.net):'—'}</td><td>${q.gstAmount?money(q.gstAmount):'—'}</td><td><b>${money(q.total)}</b></td><td class="quote-detail"><b>Includes:</b> ${esc(q.inclusions||'—')}<br><b>Notes:</b> ${esc(q.notes||'—')}</td><td><span class="pill ${q.status==='awarded'?'awarded':'open'}">${esc(q.status||'submitted')}</span></td><td><div class="quote-status-actions"><button class="btn primary" onclick="setCloudQuoteStatus('${t.id}','${q.id}','awarded')">Award</button><button class="btn" onclick="setCloudQuoteStatus('${t.id}','${q.id}','shortlisted')">Shortlist</button><button class="btn danger" onclick="setCloudQuoteStatus('${t.id}','${q.id}','declined')">Decline</button></div></td></tr>`}).join('');
 const link=publicLinkFor(t);
 const statusButtons=['Draft','Open','Closed'].map(st=>`<button class="btn ${t.status===st?'active':''}" onclick="setTenderStatus('${t.id}','${st}')">${st}</button>`).join('');
 byId('quoteModalContent').innerHTML=`<div class="modal-head"><div><h2>${esc(t.title)}</h2><small>${esc(t.eventName||'Event')} · ${esc(t.category)} · ${esc(t.region||'No region')}</small></div><button class="btn" onclick="byId('quoteModal').classList.add('hidden')">×</button></div><div class="tender-status-bar"><span class="label">Tender status</span>${statusButtons}${t.status==='Awarded'?'<span class="pill awarded">Awarded</span>':''}</div><p style="color:var(--muted)">${esc(t.brief||'No additional brief.')}</p><div class="quote-summary-grid"><div class="quote-summary-card"><span>Quotes received</span><b>${qs.length}</b></div><div class="quote-summary-card"><span>Lowest</span><b>${lowest?money(lowest):'—'}</b></div><div class="quote-summary-card"><span>Range</span><b>${priced.length>1?money(highest-lowest):'—'}</b></div><div class="quote-summary-card"><span>Awarded</span><b>${awarded?esc(awarded.company):'—'}</b></div></div><div class="section-title">Supplier link</div><div class="copy-link-box">${esc(link)}</div><div style="display:flex;gap:8px;margin-top:8px;flex-wrap:wrap"><button class="btn primary" onclick="copyTenderLink('${t.id}')">Copy Tender Link</button><button class="btn" onclick="window.open('${link}','_blank')">Preview supplier form</button><button class="btn" onclick="refreshCloudTenders().then(()=>openTenderView('${t.id}'))">Refresh quotes</button></div><div class="section-title" style="margin-top:22px">Requirements</div>${(t.requirements||[]).map(r=>`<div class="summary-row"><span>${esc(r.name)}</span><strong>${esc(r.qty)} ${esc(r.unit)}</strong></div>`).join('')||'<div class="empty">No itemised requirements.</div>'}<div class="section-title" style="margin-top:22px">Quote comparison</div>${quotes?`<div class="quote-table-wrap"><table class="quote-table"><tr><th>Supplier</th><th>Contact</th><th>Net</th><th>GST</th><th>Total</th><th>Details</th><th>Status</th><th>Decision</th></tr>${quotes}</table></div>`:'<div class="empty">No supplier quotes received yet.</div>'}<div class="section-title" style="margin-top:22px">Attachments</div><div id="tenderAttachments" class="attachment-list"><div class="empty">Checking supplier attachments…</div></div><div style="display:flex;gap:8px;margin-top:18px;flex-wrap:wrap"><button class="btn primary" onclick="editTender('${t.id}')">Edit Tender</button><button class="btn danger" onclick="deleteTender('${t.id}')">Delete tender</button></div>`;
 byId('quoteModal').classList.remove('hidden');
 loadTenderAttachments(t.id);
};

async function setTenderStatus(tenderId,label){
 if(!siteplanCloudUser)return;const map={Draft:'draft',Open:'published',Closed:'closed'};const db=map[label];if(!db)return;
 const {error}=await siteplanCloud.from('tenders').update({status:db}).eq('id',tenderId).eq('owner_id',siteplanCloudUser.id);if(error){toast(error.message);return}
 await refreshCloudTenders();openTenderView(tenderId);toast('Tender '+label.toLowerCase());
}

async function loadTenderAttachments(tenderId){
 const host=byId('tenderAttachments');if(!host||!siteplanCloudUser)return;
 try{
  const {data,error}=await siteplanCloud.from('tender_files').select('*').eq('tender_id',tenderId).order('created_at',{ascending:false});if(error)throw error;
  if(!data?.length){host.innerHTML='<div class="empty">No supplier attachments uploaded.</div>';return}
  const rows=[];for(const f of data){const path=f.storage_path||f.path||f.file_path||f.object_path;let url='';if(path){const r=await siteplanCloud.storage.from('tender-files').createSignedUrl(path,3600);url=r.data?.signedUrl||''}const name=f.file_name||f.filename||String(path||'Supplier attachment').split('/').pop();rows.push(`<div class="attachment-row"><div><b>${esc(name)}</b><br><small>${f.created_at?new Date(f.created_at).toLocaleString():''}</small></div>${url?`<a class="btn" href="${esc(url)}" target="_blank" rel="noopener">View file</a>`:'<small>File unavailable</small>'}</div>`)}host.innerHTML=rows.join('');
 }catch(e){console.warn('Tender attachments',e);host.innerHTML='<div class="empty">No accessible supplier attachments found.</div>'}
}
})();
