// SitePlan V73: cloud-first workspace + event plan sync
(()=>{
const SUPABASE_URL='https://qkvkemcqfnbmaktbxddg.supabase.co';
const SUPABASE_KEY='sb_publishable_tiPl-Y7wvfrpB7RzNzOBVA_CMIGBTwA';
if(!window.supabase?.createClient)return;
const cloud=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
let user=null,syncing=false,saveTimer=null,allowEmptyOnce=false,ready=false;
const clone=v=>JSON.parse(JSON.stringify(v));
const parse=(k,d)=>{try{return JSON.parse(localStorage.getItem(k)||JSON.stringify(d))}catch(e){return d}};
const planHasContent=p=>!!(p&&((p.markers?.length||0)||(p.shapes?.length||0)));
const when=t=>{const n=Date.parse(t||'');return Number.isFinite(n)?n:0};
const localEvents=()=>Array.isArray(typeof events!=='undefined'?events:null)?events:parse('siteplan_events',[]);
const localTenders=()=>Array.isArray(typeof tenders!=='undefined'?tenders:null)?tenders:parse('siteplan_tenders',[]);
const localSuppliers=()=>Array.isArray(typeof suppliers!=='undefined'?suppliers:null)?suppliers:parse('siteplan_suppliers',[]);
const currentKey=()=>typeof currentEventId!=='undefined'?currentEventId:(localStorage.getItem('siteplan_current_event_id')||'');
function mergeById(a,b){const out=new Map();[...(a||[]),...(b||[])].forEach(x=>{if(!x?.id)return;const old=out.get(x.id);if(!old){out.set(x.id,clone(x));return}if(when(x.updated||x.created)>=when(old.updated||old.created))out.set(x.id,clone(x));});return [...out.values()]}
function eventMeta(e){const m=clone(e||{});delete m.plan;return m}
function workspacePayload(){return {events:clone(localEvents()),tenders:clone(localTenders()),suppliers:clone(localSuppliers()),currentEventId:currentKey(),version:73,savedAt:new Date().toISOString()}}
async function session(){const {data}=await cloud.auth.getSession();user=data?.session?.user||null;return user}
async function upsertPlan(e,{forceEmpty=false}={}){if(!user||!e?.id)return;const has=planHasContent(e.plan);const {data:existing}=await cloud.from('siteplan_event_plans').select('plan_data').eq('owner_id',user.id).eq('event_key',String(e.id)).maybeSingle();if(!forceEmpty&&!has&&planHasContent(existing?.plan_data))return;await cloud.from('siteplan_event_plans').upsert({owner_id:user.id,event_key:String(e.id),event_name:e.name||e.plan?.eventName||'Untitled Event',plan_data:e.plan||null,event_meta:eventMeta(e),updated_at:new Date().toISOString()},{onConflict:'owner_id,event_key'})}
async function saveWorkspace(){if(!user||syncing)return;await cloud.from('siteplan_workspace_state').upsert({owner_id:user.id,workspace_data:workspacePayload(),updated_at:new Date().toISOString()},{onConflict:'owner_id'});const evt=localEvents().find(x=>String(x.id)===String(currentKey()));if(evt)await upsertPlan(evt,{forceEmpty:allowEmptyOnce});allowEmptyOnce=false}
function queueSave(){clearTimeout(saveTimer);saveTimer=setTimeout(()=>saveWorkspace().catch(()=>{}),450)}
async function reconcile(){if(syncing)return;syncing=true;try{if(!await session())return;const [{data:rows,error:pe},{data:ws,error:we}]=await Promise.all([cloud.from('siteplan_event_plans').select('event_key,event_name,plan_data,event_meta,updated_at').eq('owner_id',user.id),cloud.from('siteplan_workspace_state').select('workspace_data,updated_at').eq('owner_id',user.id).maybeSingle()]);if(pe||we)return;let ev=clone(localEvents()),te=clone(localTenders()),su=clone(localSuppliers());const cloudWS=ws?.workspace_data||{};ev=mergeById(ev,cloudWS.events||[]);te=mergeById(te,cloudWS.tenders||[]);su=mergeById(su,cloudWS.suppliers||[]);const map=new Map(ev.map(x=>[String(x.id),x]));for(const r of rows||[]){const key=String(r.event_key),local=map.get(key),meta=clone(r.event_meta||{}),cloudPlan=r.plan_data||null;if(!local){map.set(key,{...meta,id:key,name:r.event_name||meta.name||'Untitled Event',plan:cloudPlan,updated:r.updated_at,created:meta.created||r.updated_at,budget:Number(meta.budget||0)});continue}const localRich=planHasContent(local.plan),cloudRich=planHasContent(cloudPlan);if(cloudRich&&!localRich){local.plan=cloudPlan;local.name=r.event_name||local.name;local.updated=r.updated_at||local.updated}else if(cloudRich&&localRich&&when(r.updated_at)>when(local.updated)){local.plan=cloudPlan;local.name=r.event_name||local.name;local.updated=r.updated_at}else if(localRich&&(!cloudRich||when(local.updated)>=when(r.updated_at)))await upsertPlan(local)}ev=[...map.values()];if(typeof events!=='undefined')events=ev;if(typeof tenders!=='undefined')tenders=te;if(typeof suppliers!=='undefined')suppliers=su;localStorage.setItem('siteplan_events',JSON.stringify(ev));localStorage.setItem('siteplan_tenders',JSON.stringify(te));localStorage.setItem('siteplan_suppliers',JSON.stringify(su));const preferred=currentKey()||cloudWS.currentEventId||ev[0]?.id||'';if(preferred){if(typeof currentEventId!=='undefined')currentEventId=preferred;localStorage.setItem('siteplan_current_event_id',preferred)}if(typeof renderEvents==='function')renderEvents();if(typeof renderTenders==='function')renderTenders();if(typeof renderSupplierDashboard==='function')renderSupplierDashboard();await cloud.from('siteplan_workspace_state').upsert({owner_id:user.id,workspace_data:workspacePayload(),updated_at:new Date().toISOString()},{onConflict:'owner_id'});for(const e of ev)if(planHasContent(e.plan))await upsertPlan(e);ready=true}finally{syncing=false}}
async function recoverOne(id){if(!user)await session();if(!user)return false;const {data}=await cloud.from('siteplan_event_plans').select('event_name,plan_data,event_meta,updated_at').eq('owner_id',user.id).eq('event_key',String(id)).maybeSingle();if(!data)return false;let e=localEvents().find(x=>String(x.id)===String(id));if(!e){e={...(data.event_meta||{}),id:String(id),name:data.event_name||'Untitled Event',plan:data.plan_data||null,updated:data.updated_at,created:data.event_meta?.created||data.updated_at};if(typeof events!=='undefined')events.unshift(e)}else if(planHasContent(data.plan_data)&&(!planHasContent(e.plan)||when(data.updated_at)>when(e.updated))){e.plan=data.plan_data;e.name=data.event_name||e.name;e.updated=data.updated_at}localStorage.setItem('siteplan_events',JSON.stringify(localEvents()));return true}
function wrapCore(){if(typeof savePlan==='function'&&!savePlan.__spCloud){const old=savePlan;const wrapped=function(){const r=old.apply(this,arguments);queueSave();return r};wrapped.__spCloud=true;savePlan=wrapped}if(typeof saveEvents==='function'&&!saveEvents.__spCloud){const old=saveEvents;const wrapped=function(){const r=old.apply(this,arguments);queueSave();return r};wrapped.__spCloud=true;saveEvents=wrapped}if(typeof openEvent==='function'&&!openEvent.__spCloud){const old=openEvent;const wrapped=async function(id){try{await recoverOne(id)}catch(e){}return old.call(this,id)};wrapped.__spCloud=true;openEvent=wrapped}if(typeof deleteEvent==='function'&&!deleteEvent.__spCloud){const old=deleteEvent;const wrapped=function(id){const r=old.apply(this,arguments);if(user)cloud.from('siteplan_event_plans').delete().eq('owner_id',user.id).eq('event_key',String(id)).then(()=>queueSave());return r};wrapped.__spCloud=true;deleteEvent=wrapped}const clear=document.getElementById('clearBtn');if(clear&&!clear.dataset.spCloud){clear.dataset.spCloud='1';clear.addEventListener('click',()=>{allowEmptyOnce=true;setTimeout(()=>{allowEmptyOnce=false},5000)},true)}}
wrapCore();setTimeout(async()=>{try{await reconcile();wrapCore()}catch(e){}},700);cloud.auth.onAuthStateChange((_event,s)=>{user=s?.user||null;if(user)setTimeout(()=>reconcile().catch(()=>{}),120)});window.addEventListener('beforeunload',()=>{if(ready)queueSave()});
})();
